### ISSUE TITLE
How to add  @ZeebeWorker(timeout = 1000) timeout

### ISSUE THREAD

**Issue by cristianbriscaru** [camunda-community-hub/micronaut-zeebe-client#93]
How to add @ZeebeWorker(timeout = 1000)  timeout ?

It looks like zeebe java client supports this:  https://docs.camunda.io/docs/apis-clients/java-client-examples/job-worker-open/#jobworkercreatorjava

Thank you

**Comment by tobiasschaefer** [comment]
Hi @cristianbriscaru ,

thanks for taking the time to report that issue.

Currently the job timeout cannot be configured per worker via annotation. However, we will add the missing attributes on the annotation.

Until then it may be a workaround for you (or maybe even better :smiley: ) to configure the timeout globally for all workers, see `zeebe.client.cloud.default-job-timeout` as documented on https://github.com/camunda-community-hub/micronaut-zeebe-client#configuration

Is that an option for you?

**Comment by cristianbriscaru** [comment]
Hi @tobiasschaefer ,

The workaround should be fine for now (we usually have a worker per microservice) but having the per worker via annotation configuration would be awesome.

Thank you

**Comment by tobiasschaefer** [comment]
Hi @cristianbriscaru ,

Release v1.6.0 now supports the "timeout" property on the ZeebeWorker annotation.

Note that you don't simply pass in a value in milliseconds but a string like "PT15M" which makes it less error prone. See all currently supported annotation properties here: https://github.com/camunda-community-hub/micronaut-zeebe-client#zeebeworker-annotation

Does this solve your issue?
